name: "Exasol Cluster"
description: "Instantiates an Exasol database cluster"
inputs:
  exasol-version:
    description: "Version of the Exasol database"
    required: true
  num-nodes:
    description: "Number of nodes to spawn in the cluster"
    required: true
outputs:
  url:
    description: "Connection string for the database"
    value: ${{ steps.connection-string.outputs.url }}
runs:
  using: "composite"
  steps:
    - name: Restore Exasol image
      id: cache-docker-exasol
      uses: actions/cache@v3
      with:
        path: ~/ci/cache/docker
        key: cache-docker-exasol-${{ inputs.exasol-version }}

    - name: Store Exasol image if cache miss
      if: steps.cache-docker-exasol.outputs.cache-hit != 'true'
      run: docker pull exasol/docker-db:${{ inputs.exasol-version }} && mkdir -p ~/ci/cache/docker && docker image save exasol/docker-db:${{ inputs.exasol-version }} --output ~/ci/cache/docker/exasol-${{ inputs.exasol-version }}.tar
      shell: bash

    - name: Load Exasol image
      run: docker image load --input ~/ci/cache/docker/exasol-${{ inputs.exasol-version }}.tar
      shell: bash

    - name: Set up Docker network
      run: docker network create --driver=bridge --subnet=10.10.10.0/24 sqlx
      shell: bash

    - name: Initialize Exasol cluster
      run: |
        #############################
        #### Create initial node ####
        #############################

        docker run -v $HOME/sqlx1:/exa --rm --privileged -i exasol/docker-db:${{ inputs.exasol-version }} init-sc --template --num-nodes ${{ inputs.num-nodes }}
        docker run --rm -v $HOME/sqlx1:/exa exasol/docker-db:${{ inputs.exasol-version }} exaconf modify-volume -n DataVolume1 -s 4GiB
        sudo truncate -s 6G $HOME/sqlx1/data/storage/dev.1
        
        ####################
        #### Clone node ####
        ####################

        for (( i=2; i<=${{ inputs.num-nodes }}; i++ )); do
          sudo cp -R $HOME/sqlx1 $HOME/sqlx$i
        done
        
        ################################
        #### Generate TLS 1.3 certs ####
        ################################
        
        sudo openssl genpkey -algorithm RSA -out ~/sqlx1/etc/ssl/ssl.ca.key -pkeyopt rsa_keygen_bits:2048
        sudo openssl genpkey -algorithm RSA -out ~/sqlx1/etc/ssl/ssl.key -pkeyopt rsa_keygen_bits:2048
        
        echo "basicConstraints=CA:FALSE" > $HOME/v3.ext
        echo "keyUsage=digitalSignature,keyEncipherment" >> $HOME/v3.ext
        echo "extendedKeyUsage=clientAuth,serverAuth" >> $HOME/v3.ext
        echo "subjectAltName=DNS:exacluster.local" >> $HOME/v3.ext
        
        sudo openssl req -x509 -new -nodes -key $HOME/sqlx1/etc/ssl/ssl.ca.key -sha256 -days 3650 -out $HOME/sqlx1/etc/ssl/ssl.ca -subj "/CN=exacluster.local"
        sudo openssl req -new -key $HOME/sqlx1/etc/ssl/ssl.key -out $HOME/ssl.csr -subj "/CN=exacluster.local"
        sudo openssl x509 -req -in $HOME/ssl.csr -CA $HOME/sqlx1/etc/ssl/ssl.ca -CAkey $HOME/sqlx1/etc/ssl/ssl.ca.key -CAcreateserial -out $HOME/sqlx1/etc/ssl/ssl.crt -days 365 -sha256 -extfile $HOME/v3.ext

      shell: bash

    - name: Start Exasol cluster
      run: |
        for (( i=1; i<=${{ inputs.num-nodes }}; i++ )); do
          docker run --name sqlx$i --detach --network=sqlx --ip 10.10.10.1$i --privileged --stop-timeout 120 -v $HOME/sqlx$i:/exa exasol/docker-db:${{ inputs.exasol-version }} init-sc --node-id 1$i
        done
      shell: bash

    - name: Wait until Exasol cluster is live
      run: |
        set +e
        RC=1

        while [[ $RC -ne 0 ]]; do
          docker exec sqlx1 /bin/bash -c '`find /usr/opt -name exaplus | head -1` -c localhost:8563 -u sys -p exasol -sql "SELECT * FROM DUAL;"' &>/dev/null
          RC=$?
          sleep 5
        done
      shell: bash

    - name: Create connection string
      id: connection-string
      run: echo "url=exa://sys:exasol@10.10.10.11..1$NUM_NODES:8563" >> $GITHUB_OUTPUT
      shell: bash
