name: "Exasol Cluster"
description: "Instantiates an Exasol database cluster"
inputs:
  exasol-version:
    description: "Version of the Exasol database"
    required: true
  num-nodes:
    description: "Number of nodes to spawn in the cluster"
    required: true
outputs:
  no-tls-url:
    description: "Connection string for the database with TLS disabled"
    value: ${{ steps.connection-strings.outputs.no-tls-url }}
  tls-url:
    description: "Connection string for the database with TLS enabled"
    value: ${{ steps.connection-strings.outputs.tls-url }}
runs:
  using: "composite"
  steps:
    - name: Restore Exasol image
      id: cache-docker-exasol
      uses: actions/cache@v3
      with:
        path: ~/ci/cache/docker
        key: cache-docker-exasol-${{ inputs.exasol-version }}

    - name: Store Exasol image if cache miss
      if: steps.cache-docker-exasol.outputs.cache-hit != 'true'
      run: docker pull exasol/docker-db:${{ inputs.exasol-version }} && mkdir -p ~/ci/cache/docker && docker image save exasol/docker-db:${{ inputs.exasol-version }} --output ~/ci/cache/docker/exasol-${{ inputs.exasol-version }}.tar
      shell: bash

    - name: Load Exasol image
      run: docker image load --input ~/ci/cache/docker/exasol-${{ inputs.exasol-version }}.tar
      shell: bash

    - name: Set up Exasol Cluster
      run: |
        docker network create --driver=bridge --subnet=10.10.10.0/24 sqlx

        docker run -v $HOME/sqlx1:/exa --rm --privileged -i exasol/docker-db:7.0.22 init-sc --template --num-nodes 3
        docker run --rm -v $HOME/sqlx1:/exa exasol/docker-db:7.0.22 exaconf modify-volume -n DataVolume1 -s 4GiB
        sudo truncate -s 6G $HOME/sqlx1/data/storage/dev.1
        sudo cp -R $HOME/sqlx1 $HOME/sqlx2
        sudo cp -R $HOME/sqlx1 $HOME/sqlx3

        docker run --name sqlx1 --detach --network=sqlx --ip 10.10.10.11 --privileged --stop-timeout 120 -v $HOME/sqlx1:/exa exasol/docker-db:7.0.22 init-sc --node-id 11
        docker run --name sqlx2 --detach --network=sqlx --ip 10.10.10.12 --privileged --stop-timeout 120 -v $HOME/sqlx2:/exa exasol/docker-db:7.0.22 init-sc --node-id 12
        docker run --name sqlx3 --detach --network=sqlx --ip 10.10.10.13 --privileged --stop-timeout 120 -v $HOME/sqlx3:/exa exasol/docker-db:7.0.22 init-sc --node-id 13
      shell: bash

    # The exadt tool always creates the Exasol cluster with this subnet
    - name: Create connection strings
      id: connection-strings
      run: |
        DATABASE_URL="exa://sys:exasol@10.10.10.11..1$NUM_NODES:8563"
        echo "no-tls-url=$DATABASE_URL?ssl-mode=disabled" >> $GITHUB_OUTPUT
        echo "tls-url=$DATABASE_URL?ssl-mode=required" >> $GITHUB_OUTPUT
      shell: bash
