# rust-analyzer can be configured with nightly rustfmt
# i.e. for vscode in settings.json:
#    "rust-analyzer.rustfmt.extraArgs": [
#        "+nightly"
#    ],

unstable_features = true
style_edition = "2021"
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
format_code_in_doc_comments = true
format_macro_bodies = true
format_macro_matchers = true
format_strings = true
normalize_doc_attributes = true
wrap_comments = true
comment_width = 100
