name: "Free disk space"
description: "Deletes language runtimes and implicit docker images to free up space in the runner"
runs:
  using: "composite"
  steps:
    - name: Get initial disk space
      run: |
        echo "Getting initial free space"
        df . -h
      shell: bash

    - name: Remove language runtimes
      run: |
        sudo rm -rf \
          /usr/share/dotnet /usr/local/lib/android /opt/ghc \
          /usr/local/share/powershell /usr/share/swift /usr/local/.ghcup \
          /usr/lib/jvm /opt/hostedtoolcache/CodeQL || true

        echo "Removed language runtimes"
        df . -h
      shell: bash

    - name: Remove docker images
      run: |
        sudo docker image prune --all --force

        echo "Removed docker images"
        df . -h
      shell: bash
