# yaml-language-server: $schema=./main.yaml
name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  format:
    name: Format
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt

      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check

  clippy:
    name: Clippy
    needs: format
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        etl: [etl_native_tls, etl_rustls, etl]
        compression: [",compression", ""]
        features: [",migrate,rust_decimal,uuid,chrono", ""]
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: clippy

      - uses: Swatinem/rust-cache@v2

      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --tests --features ${{ matrix.etl }}${{ matrix.features }}${{ matrix.compression }}
        env:
          RUSTFLAGS: -D warnings

  test:
    name: Testing
    needs: clippy
    runs-on: ubuntu-20.04
    services:
      exasol:
        image: exasol/docker-db:7.0.22
        ports:
          - 8563:8563
        options: --privileged
    steps:
      - uses: actions/checkout@v3

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Create connection strings
        run: |
          echo "NO_TLS_URL=exa://sys:exasol@127.0.0.1:8563?ssl-mode=disabled" >> $GITHUB_ENV
          echo "TLS_URL=exa://sys:exasol@127.0.0.1:8563?ssl-mode=required" >> $GITHUB_ENV

      - name: Run tests
        run: |
          # Tests not requiring a connection
          cargo test

          # Connection tests without compression
          DATABASE_URL=${{ env.NO_TLS_URL }} cargo test --features migrate,rust_decimal,uuid,chrono
          DATABASE_URL=${{ env.TLS_URL }} cargo test --features migrate,rust_decimal,uuid,chrono

          # Connection tests with compression
          DATABASE_URL=${{ env.NO_TLS_URL }} cargo test --features migrate,compression -- --ignored
          DATABASE_URL=${{ env.TLS_URL }} cargo test --features migrate,compression -- --ignored

          # ETL without TLS feature but TLS connection (should fail)
          DATABASE_URL=${{ env.TLS_URL }} cargo test --features migrate,etl -- --ignored --nocapture --test-threads 4 && exit 1

          # ETL tests without compression
          DATABASE_URL=${{ env.NO_TLS_URL }} cargo test --features migrate,etl -- --ignored --nopcature --test-threads 4
          DATABASE_URL=${{ env.TLS_URL }} cargo test --features migrate,etl_native_tls -- --ignored --nopcature --test-threads 4
          DATABASE_URL=${{ env.TLS_URL }} cargo test --features migrate,etl_rustls -- --ignored --nopcature --test-threads 4

          # ETL non-TLS tests when TLS feature is provided (resorts to non-TLS)
          DATABASE_URL=${{ env.NO_TLS_URL }} cargo test --features migrate,etl_native_tls -- --ignored --nopcature --test-threads 4
          DATABASE_URL=${{ env.NO_TLS_URL }} cargo test --features migrate,etl_rustls -- --ignored --nopcature --test-threads 4

          # ETL tests with compression
          DATABASE_URL=${{ env.NO_TLS_URL }} cargo test --features etl,compression -- --ignored --nopcature  --test-threads 4
          DATABASE_URL=${{ env.TLS_URL }} cargo test --features migrate,etl_native_tls,compression -- --ignored --nopcature  --test-threads 4
          DATABASE_URL=${{ env.TLS_URL }} cargo test --features migrate,etl_rustls,compression -- --ignored --nopcature --test-threads 4
