# yaml-language-server: $schema=./main.yaml
name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv

      - uses: actions/checkout@v3
        with:
          repository: Exasol/docker-db
          ref: "7.0.22"

      - name: Set up Exasol Cluster
        run: |
          docker pull exasol/docker-db:7.0.22
          pipenv install -r exadt_requirements.txt
          pipenv run ./exadt create-cluster --root ~/sqlx/ --create-root sqlx
          pipenv run ./exadt init-cluster --image exasol/docker-db:7.0.22 --license ./license/license.xml --num-nodes 3 --auto-storage sqlx
          pipenv run ./exadt start-cluster sqlx

      - name: Create connection strings
        run: |
          CONTAINER_ID=`docker ps --format "table {{.ID}}\t" | head -2 | tail -1`
          EXA_IP=`docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $CONTAINER_ID`
          echo "NO_TLS_URL=exa://sys:exasol@$EXA_IP:8563?ssl-mode=disabled" >> $GITHUB_ENV
          echo "TLS_URL=exa://sys:exasol@$EXA_IP:8563" >> $GITHUB_ENV

      - uses: actions/checkout@v3

      - name: Run tests
        run: docker run --rm --network=sqlx_priv -e DATABASE_URL=${{ env.TLS_URL }} -v "$PWD":/usr/src/sqlx-exasol -w /usr/src/sqlx-exasol rust:1.72.0 cargo test --features migrate,compression,etl_native_tls -- --ignored --nocapture --test-threads 4
